app_home:
    path: /
    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_running_create:
    path: /running/create
    controller: App\Controller\RunningController::createOrUpdate

app_running_update:
    path: /running/update/{running}
    controller: App\Controller\RunningController::createOrUpdate

app_running_delete:
    path: /running/delete/{running}
    controller: App\Controller\RunningController::delete

app_registration:
    path: /registration
    controller: App\Controller\RegistrationController::registration